export const temporaryData = [
  {
    id: "1",
    img: "/image/auto/img1.png",
    year: 2012,
    brand: "Volkswagen Polo Hatch",
    price: "R109,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "2",
    img: "/image/auto/img2.png",
    year: 2012,
    brand: "Volkswagen Polo Hatch Volkswagen Polo Hatch llllll",
    price: "R109,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "3",
    img: "/image/auto/img3.png",
    year: 2012,
    brand: "Volkswagen Polo Hatch",
    price: "R109,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "4",
    img: "/image/auto/img4.png",
    year: 2012,
    brand: "Volkswagen Polo Hatch",
    price: "R109,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "5",
    img: "/image/auto/img1.png",
    year: 2013,
    brand: "Volkswagen Polo Hatch",
    price: "R119,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "6",
    img: "/image/auto/img2.png",
    year: 2013,
    brand: "Volkswagen Polo Hatch",
    price: "R119,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "7",
    img: "/image/auto/img3.png",
    year: 2013,
    brand: "Volkswagen Polo Hatch",
    price: "R119,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "8",
    img: "/image/auto/img4.png",
    year: 2013,
    brand: "Volkswagen Polo Hatch",
    price: "R119,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "9",
    img: "/image/auto/img1.png",
    year: 2014,
    brand: "Volkswagen Polo Hatch",
    price: "R129,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "10",
    img: "/image/auto/img2.png",
    year: 2014,
    brand: "Volkswagen Polo Hatch",
    price: "R129,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "11",
    img: "/image/auto/img3.png",
    year: 2014,
    brand: "Volkswagen Polo Hatch",
    price: "R129,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "12",
    img: "/image/auto/img4.png",
    year: 2014,
    brand: "Volkswagen Polo Hatch",
    price: "R129,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "13",
    img: "/image/auto/img1.png",
    year: 2015,
    brand: "Volkswagen Polo Hatch",
    price: "R139,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "14",
    img: "/image/auto/img2.png",
    year: 2015,
    brand: "Volkswagen Polo Hatch",
    price: "R139,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "15",
    img: "/image/auto/img3.png",
    year: 2015,
    brand: "Volkswagen Polo Hatch",
    price: "R139,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "16",
    img: "/image/auto/img4.png",
    year: 2015,
    brand: "Volkswagen Polo Hatch",
    price: "R139,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "17",
    img: "/image/auto/img1.png",
    year: 2016,
    brand: "Volkswagen Polo Hatch",
    price: "R149,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "18",
    img: "/image/auto/img2.png",
    year: 2016,
    brand: "Volkswagen Polo Hatch",
    price: "R149,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "19",
    img: "/image/auto/img3.png",
    year: 2016,
    brand: "Volkswagen Polo Hatch",
    price: "R149,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "20",
    img: "/image/auto/img4.png",
    year: 2016,
    brand: "Volkswagen Polo Hatch",
    price: "R149,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "21",
    img: "/image/auto/img1.png",
    year: 2017,
    brand: "Volkswagen Polo Hatch",
    price: "R159,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "22",
    img: "/image/auto/img2.png",
    year: 2017,
    brand: "Volkswagen Polo Hatch",
    price: "R159,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "23",
    img: "/image/auto/img3.png",
    year: 2017,
    brand: "Volkswagen Polo Hatch",
    price: "R159,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "24",
    img: "/image/auto/img4.png",
    year: 2017,
    brand: "Volkswagen Polo Hatch",
    price: "R159,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "25",
    img: "/image/auto/img1.png",
    year: 2018,
    brand: "Volkswagen Polo Hatch",
    price: "R169,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "26",
    img: "/image/auto/img2.png",
    year: 2018,
    brand: "Volkswagen Polo Hatch",
    price: "R169,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "27",
    img: "/image/auto/img3.png",
    year: 2018,
    brand: "Volkswagen Polo Hatch",
    price: "R169,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "28",
    img: "/image/auto/img4.png",
    year: 2018,
    brand: "Volkswagen Polo Hatch",
    price: "R169,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "29",
    img: "/image/auto/img1.png",
    year: 2019,
    brand: "Volkswagen Polo Hatch",
    price: "R179,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "30",
    img: "/image/auto/img2.png",
    year: 2019,
    brand: "Volkswagen Polo Hatch",
    price: "R179,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "31",
    img: "/image/auto/img3.png",
    year: 2019,
    brand: "Volkswagen Polo Hatch",
    price: "R179,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "32",
    img: "/image/auto/img4.png",
    year: 2019,
    brand: "Volkswagen Polo Hatch",
    price: "R179,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "33",
    img: "/image/auto/img1.png",
    year: 2020,
    brand: "Volkswagen Polo Hatch",
    price: "R189,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "34",
    img: "/image/auto/img2.png",
    year: 2020,
    brand: "Volkswagen Polo Hatch",
    price: "R189,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "35",
    img: "/image/auto/img3.png",
    year: 2020,
    brand: "Volkswagen Polo Hatch",
    price: "R189,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "36",
    img: "/image/auto/img4.png",
    year: 2020,
    brand: "Volkswagen Polo Hatch",
    price: "R189,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "37",
    img: "/image/auto/img1.png",
    year: 2021,
    brand: "Volkswagen Polo Hatch",
    price: "R199,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "38",
    img: "/image/auto/img2.png",
    year: 2021,
    brand: "Volkswagen Polo Hatch",
    price: "R199,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "39",
    img: "/image/auto/img3.png",
    year: 2021,
    brand: "Volkswagen Polo Hatch",
    price: "R199,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "40",
    img: "/image/auto/img4.png",
    year: 2021,
    brand: "Volkswagen Polo Hatch",
    price: "R199,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "41",
    img: "/image/auto/img1.png",
    year: 2022,
    brand: "Volkswagen Polo Hatch",
    price: "R209,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "42",
    img: "/image/auto/img2.png",
    year: 2022,
    brand: "Volkswagen Polo Hatch",
    price: "R209,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "43",
    img: "/image/auto/img3.png",
    year: 2022,
    brand: "Volkswagen Polo Hatch",
    price: "R209,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "44",
    img: "/image/auto/img4.png",
    year: 2022,
    brand: "Volkswagen Polo Hatch",
    price: "R209,900",
    active: false,
    deposit: false,
    archive: true,
  },
  {
    id: "45",
    img: "/image/auto/img1.png",
    year: 2023,
    brand: "Volkswagen Polo Hatch",
    price: "R219,900",
    active: true,
    deposit: false,
    archive: false,
  },
  {
    id: "46",
    img: "/image/auto/img2.png",
    year: 2023,
    brand: "Volkswagen Polo Hatch",
    price: "R219,900",
    active: false,
    deposit: true,
    archive: true,
  },
  {
    id: "47",
    img: "/image/auto/img3.png",
    year: 2023,
    brand: "Volkswagen Polo Hatch",
    price: "R219,900",
    active: true,
    deposit: true,
    archive: false,
  },
  {
    id: "48",
    img: "/image/auto/img4.png",
    year: 2023,
    brand: "Volkswagen Polo Hatch",
    price: "R219,900",
    active: false,
    deposit: false,
    archive: true,
  }
];
