import type { Metadata } from "next";
import localFont from "next/font/local";
import { Metrophobic, Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/modules/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const metrophobic = Metrophobic({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} ${geistMono.className} ${workSans.className} ${metrophobic.className}`}
    >
      <body className="bg-background text-textColor">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
