import { nanoid } from "nanoid";

export const temporary = [
  {
    title: "Overview",
    inputs: [
      { id: nanoid(), label: "make", name: "make", value: "Acura", options: [
          { id: nanoid(), value: "Acura", text: "Acura" },
          { id: nanoid(), value: "Alfa Romeo", text: "Alfa Romeo" },
          { id: nanoid(), value: "Audi", text: "Audi" },
          { id: nanoid(), value: "BMW", text: "BMW" },
          { id: nanoid(), value: "Cadillac", text: "Cadillac" },
          { id: nanoid(), value: "Chevrolet", text: "Chevrolet" },
          { id: nanoid(), value: "Chrysler", text: "Chrysler" },
          { id: nanoid(), value: "Citroën", text: "Citroën" },
          { id: nanoid(), value: "Dodge", text: "Dodge" },
          { id: nanoid(), value: "Fiat", text: "Fiat" },
          { id: nanoid(), value: "Genesis", text: "Genesis" },
          { id: nanoid(), value: "GMC", text: "GMC" },
          { id: nanoid(), value: "Honda", text: "Honda" },
          { id: nanoid(), value: "Hyundai", text: "Hyundai" },
          { id: nanoid(), value: "Infiniti", text: "Infiniti" },
          { id: nanoid(), value: "Jaguar", text: "Jaguar" },
          { id: nanoid(), value: "Jeep", text: "Jeep" },
          { id: nanoid(), value: "Kia", text: "Kia" },
          { id: nanoid(), value: "Land Rover", text: "Land Rover" },
          { id: nanoid(), value: "Lexus", text: "Lexus" },
          { id: nanoid(), value: "Mercedes-Benz", text: "Mercedes-Benz" },
          { id: nanoid(), value: "Mini", text: "Mini" },
          { id: nanoid(), value: "Mitsubishi", text: "Mitsubishi" },
          { id: nanoid(), value: "Nissan", text: "Nissan" },
          { id: nanoid(), value: "Opel", text: "Opel" },
          { id: nanoid(), value: "Peugeot", text: "Peugeot" },
          { id: nanoid(), value: "Porsche", text: "Porsche" },
          { id: nanoid(), value: "Renault", text: "Renault" },
          { id: nanoid(), value: "Rolls-Royce", text: "Rolls-Royce" },
          { id: nanoid(), value: "Saab", text: "Saab" },
          { id: nanoid(), value: "Škoda", text: "Škoda" },
          { id: nanoid(), value: "Subaru", text: "Subaru" },
          { id: nanoid(), value: "Suzuki", text: "Suzuki" },
          { id: nanoid(), value: "Tesla", text: "Tesla" },
          { id: nanoid(), value: "Toyota", text: "Toyota" },
          { id: nanoid(), value: "Volkswagen", text: "Volkswagen" },
          { id: nanoid(), value: "Volvo", text: "Volvo" },
          { id: nanoid(), value: "Datsun", text: "Datsun" },
          { id: nanoid(), value: "Golden Journey", text: "Golden Journey" },
          { id: nanoid(), value: "Mazda", text: "Mazda" },
          { id: nanoid(), value: "BAIC", text: "BAIC" },
          { id: nanoid(), value: "Daewoo", text: "Daewoo" },
          { id: nanoid(), value: "Gwm", text: "Gwm" },
          { id: nanoid(), value: "JAC", text: "JAC" },
          { id: nanoid(), value: "Tata", text: "Tata" },
          { id: nanoid(), value: "Daihatsu", text: "Daihatsu" },
          { id: nanoid(), value: "Ford", text: "Ford" },
          { id: nanoid(), value: "JMC", text: "JMC" },
          { id: nanoid(), value: "Chery", text: "Chery" },
              { id: nanoid(), value: "Haval", text: "Haval" },
              { id: nanoid(), value: "Isuzu", text: "Isuzu" },
              { id: nanoid(), value: "Geely", text: "Geely" },
              { id: nanoid(), value: "Geely", text: "Geely" },
              { id: nanoid(), value: "Chana", text: "Smart" },
              { id: nanoid(), value: "Seat", text: "Seat" },
              { id: nanoid(), value: "Mahindra", text: "Mahindra" },
        ] },
      { id: nanoid(), label: "km", name:"mileageInKm", value: "", mask: true },
      { id: nanoid(), label: "model", name: "model", value: "" },
      { id: nanoid(), label: "fuel", name: "fuelType", value: "petrol", options: [
          { id: nanoid(), value: "petrol", text: "petrol" },
          { id: nanoid(), value: "diesel", text: "diesel" },
          { id: nanoid(), value: "hybrid", text: "hybrid" },
        ] },
      { id: nanoid(), label: "year", name: "year", value: "", mask: true },
      { id: nanoid(), label: "transmission", name: "transmission", value: "manual", options: [
          { id: nanoid(), value: "manual", text: "manual" },
          { id: nanoid(), value: "automatic", text: "automatic" },
        ] },
      { id: nanoid(), label: "price", name: "price", value: "", mask: true },
      { id: nanoid(), label: "drive type", name: "driveType", value: "FWD", options: [
              { id: nanoid(), value: "FWD", text: "FWD" },
              { id: nanoid(), value: "RWD", text: "RWD" },
              { id: nanoid(), value: "AWD", text: "AWD" },
              { id: nanoid(), value: "4X4", text: "4X4" },
          ] },
      { id: nanoid(), label: "finance", name: "finance", value: "" },
      { id: nanoid(), label: "Select car type", name: "type", value: "car", options: [
          { id: nanoid(), value: "car", text: "car" },
          { id: nanoid(), value: "bakkie", text: "bakkie" },
          { id: nanoid(), value: "commercial", text: "commercial" },
        ] },
    ],
  },
  {
    title: "Details",
    inputs: [
      { id: nanoid(), label: "fuel consumption", name: "fuel_consumption", value: "" },
      { id: nanoid(), label: "body type", name: "body_type", value: "sedan", options: [
              { id: nanoid(), value: "sedan", text: "sedan" },
              { id: nanoid(), value: "stationWagon", text: "station wagon" },
              { id: nanoid(), value: "SUV", text: "SUV" },
              { id: nanoid(), value: "coupe", text: "coupe" },
              { id: nanoid(), value: "hatchback", text: "hatchback" },
              { id: nanoid(), value: "roadster", text: "roadster" },
              { id: nanoid(), value: "Van", text: "Van" },
              { id: nanoid(), value: "minibus", text: "Minibus" },
              { id: nanoid(), value: "MPV", text: "MPV" },
              { id: nanoid(), value: "singleCab", text: "Single Cab" },
              { id: nanoid(), value: "doubleCab", text: "Double Cab" },
              { id: nanoid(), value: "cabriolet", text: "Cabriolet" },
          ] },
      { id: nanoid(), label: "engine capacity", name: "engine_capacity", value: "" },
      { id: nanoid(), label: "variant", name: "variant", value: "" },
      { id: nanoid(), label: "number of seats", name: "number_of_seats", value: "", mask: true },
      { id: nanoid(), label: "colour", name: "colour", value: "" },
      { id: nanoid(), label: "number of doors", name: "number_of_doors", value: "", mask: true },
      { id: nanoid(), label: "stock number", name: "stock_number", value: "" },
    ],
  },
  {
    title: "conditions",
    inputs: [
      { id: nanoid(), label: "vehicle service History", name: "vehicle_service_history", value: "full SH", options: [
              { id: nanoid(), value: "full SH", text: "full SH" },
              { id: nanoid(), value: "Partial", text: "Partial" },
              { id: nanoid(), value: "Null", text: "Null" },
          ] },
      { id: nanoid(), label: "roadworthy voucher", name: "roadworthy_voucher", value: "", isFileInput: true },
      { id: nanoid(), label: "spare key", name: "spare_key", value: true, toggle: true },
      { id: nanoid(), label: "condition report", name: "condition_report", value: "", isFileInput: true },
      { id: nanoid(), label: "Warranty", name: "warranty", value: true, toggle: true },
    ],
  },
  {
    title: "perfomance",
    inputs: [
      { id: nanoid(), label: "kilowatts", name: "kilowatts", value: "", mask: true },
      { id: nanoid(), label: "cylinder layout", name: "cylinder_layout", value: "" },
      { id: nanoid(), label: "gears", name: "gears", value: "", mask: true },
    ],
  },
  {
    title: "Featurers",
    inputs: [
      { id: nanoid(), label: "feature 1", name: "feature_1", value: "" },
      { id: nanoid(), label: "feature 4", name: "feature_2", value: "" },
      { id: nanoid(), label: "feature 2", name: "feature_3", value: "" },
      { id: nanoid(), label: "feature 5", name: "feature_4", value: "" },
      { id: nanoid(), label: "feature 3", name: "feature_5", value: "" },
      { id: nanoid(), label: "feature 6", name: "feature_6", value: "" },
    ],
  },
];
