export const temporaryData = [
  {
    id: 1,
    name: "Humeniuk Alina",
    addingDate: "01.01.2022",
    status: "verified",
    mail: "user0@gmail.com",
    phone: "+380 93 000 73 01",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: true,
  },
  {
    id: 2,
    name: "Surname Name",
    addingDate: "05.02.2023",
    status: "in progress",
    mail: "user1@gmail.com",
    phone: "+380 93 000 73 02",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: false,
  },
  {
    id: 3,
    name: "Ivanov Petr",
    addingDate: "15.03.2021",
    status: "no documents",
    mail: "user2@gmail.com",
    phone: "+380 93 000 73 03",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 4,
    name: "Kovalenko Oleg",
    addingDate: "25.06.2024",
    status: "verified",
    mail: "user3@gmail.com",
    phone: "+380 93 000 73 04",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: true,
  },
  {
    id: 5,
    name: "Petrenko Elena",
    addingDate: "30.08.2020",
    status: "in progress",
    mail: "user4@gmail.com",
    phone: "+380 93 000 73 05",
    deposit: "Yes",
    regular: true,
    dealer: true,
    archive: false,
  },
  {
    id: 6,
    name: "Shevchenko Taras",
    addingDate: "17.12.2022",
    status: "no documents",
    mail: "user5@gmail.com",
    phone: "+380 93 000 73 06",
    deposit: "No",
    regular: false,
    dealer: false,
    archive: true,
  },
  {
    id: 7,
    name: "Zhdanova Maria",
    addingDate: "19.11.2021",
    status: "verified",
    mail: "user6@gmail.com",
    phone: "+380 93 000 73 07",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 8,
    name: "Nikolaev Dmytro",
    addingDate: "10.05.2023",
    status: "in progress",
    mail: "user7@gmail.com",
    phone: "+380 93 000 73 08",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: true,
  },
  {
    id: 9,
    name: "Bondarenko Olga",
    addingDate: "22.09.2022",
    status: "no documents",
    mail: "user8@gmail.com",
    phone: "+380 93 000 73 09",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 10,
    name: "Tymoshenko Iryna",
    addingDate: "12.04.2020",
    status: "verified",
    mail: "user9@gmail.com",
    phone: "+380 93 000 73 10",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: true,
  },
  {
    id: 11,
    name: "Humeniuk Alina",
    addingDate: "01.01.2023",
    status: "verified",
    mail: "user10@gmail.com",
    phone: "+380 93 000 73 11",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 12,
    name: "Surname Name",
    addingDate: "11.02.2021",
    status: "in progress",
    mail: "user11@gmail.com",
    phone: "+380 93 000 73 12",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: true,
  },
  {
    id: 13,
    name: "Ivanov Petr",
    addingDate: "15.07.2024",
    status: "verified",
    mail: "user12@gmail.com",
    phone: "+380 93 000 73 13",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 14,
    name: "Kovalenko Oleg",
    addingDate: "20.06.2022",
    status: "no documents",
    mail: "user13@gmail.com",
    phone: "+380 93 000 73 14",
    deposit: "Yes",
    regular: false,
    dealer: true,
    archive: false,
  },
  {
    id: 15,
    name: "Petrenko Elena",
    addingDate: "28.03.2024",
    status: "in progress",
    mail: "user14@gmail.com",
    phone: "+380 93 000 73 15",
    deposit: "No",
    regular: false,
    dealer: false,
    archive: true,
  },
  {
    id: 16,
    name: "Shevchenko Taras",
    addingDate: "10.11.2020",
    status: "verified",
    mail: "user15@gmail.com",
    phone: "+380 93 000 73 16",
    deposit: "Yes",
    regular: true,
    dealer: true,
    archive: false,
  },
  {
    id: 17,
    name: "Zhdanova Maria",
    addingDate: "22.04.2023",
    status: "in progress",
    mail: "user16@gmail.com",
    phone: "+380 93 000 73 17",
    deposit: "No",
    regular: false,
    dealer: false,
    archive: true,
  },
  {
    id: 18,
    name: "Nikolaev Dmytro",
    addingDate: "09.09.2020",
    status: "no documents",
    mail: "user17@gmail.com",
    phone: "+380 93 000 73 18",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 19,
    name: "Bondarenko Olga",
    addingDate: "14.12.2021",
    status: "verified",
    mail: "user18@gmail.com",
    phone: "+380 93 000 73 19",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: true,
  },
  {
    id: 20,
    name: "Tymoshenko Iryna",
    addingDate: "23.01.2023",
    status: "in progress",
    mail: "user19@gmail.com",
    phone: "+380 93 000 73 20",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 21,
    name: "Humeniuk Alina",
    addingDate: "04.07.2024",
    status: "no documents",
    mail: "user20@gmail.com",
    phone: "+380 93 000 73 21",
    deposit: "Yes",
    regular: false,
    dealer: true,
    archive: false,
  },
  {
    id: 22,
    name: "Surname Name",
    addingDate: "13.05.2020",
    status: "verified",
    mail: "user21@gmail.com",
    phone: "+380 93 000 73 22",
    deposit: "No",
    regular: false,
    dealer: false,
    archive: true,
  },
  {
    id: 23,
    name: "Ivanov Petr",
    addingDate: "29.10.2023",
    status: "in progress",
    mail: "user22@gmail.com",
    phone: "+380 93 000 73 23",
    deposit: "Yes",
    regular: true,
    dealer: false,
    archive: false,
  },
  {
    id: 24,
    name: "Kovalenko Oleg",
    addingDate: "10.03.2021",
    status: "no documents",
    mail: "user23@gmail.com",
    phone: "+380 93 000 73 24",
    deposit: "No",
    regular: false,
    dealer: true,
    archive: false,
  },
  {
    id: 25,
    name: "Petrenko Elena",
    addingDate: "15.06.2022",
    status: "verified",
    mail: "user24@gmail.com",
    phone: "+380 93 000 73 25",
    deposit: "Yes",
    regular: true,
    dealer: true,
    archive: true,
  },
];
